### ISSUE TITLE
Add support for SQL Server

### ISSUE THREAD

**Issue by timsuchanek** [blakeembrey/sql-template-tag#18]
While Postgres is using `$1`, `$2` etc for parameter substitution, in Microsoft SQL Server it is `@P1`, `@P2` etc.

We need support for that in Prisma https://github.com/prisma/prisma/issues/3861

We can also totally do the PR and tests for that :)

**Comment by blakeembrey** [comment]
Do you happen to know if the driver reads from a different parameter (i.e. this can work automatically) or whether we need to do it via some configuration? Either way shouldn't be a big deal, here's how we generate the param list for postgres: https://github.com/blakeembrey/sql-template-tag/blob/a10d0349f5ffdd0d248edb760b1102aec461517f/src/index.ts#L71-L73. It's really simple, I'd just want to make sure we don't degrade performance.

**Comment by madebysid** [comment]
Hey! I work with Prisma and I wanted to pick this up, so I did some research.

As I understand it, this library supports the packages [`pg`](https://www.npmjs.com/package/pg) & [`mysql`](https://www.npmjs.com/package/mysql). In order to support SQL Server, I think you'd need to add support for [`mssql`](https://www.npmjs.com/package/mssql). It seems to be the library that [Microsoft endorses](https://docs.microsoft.com/en-us/sql/connect/node-js/node-js-driver-for-sql-server?view=sql-server-ver15).

However, the `mssql` package already has support for prepared statements, and as far as I can tell, there's no simple way to send out a prepared-statement-style query with parameters like `pg` & `mysql` allow you to do.

What I'm getting at is that I don't think `sql-template-tag` can "support" SQL Server. I think this issue can be closed, as it is a no-op.

Hopefully I made myself clear, please let me know if I'm mistaken!

PS: As far as https://github.com/prisma/prisma/issues/3861 goes, I do not think that it is this library reponsibility to support MSSQL, we would need to add logic for generating valid MSSQL statements in ttps://github.com/prisma/prisma itself.

**Comment by blakeembrey** [comment]
We can probably open a PR to `mssql`, from what I can see there’s the `input` method that just internally sets `this.parameters`. That would be one way to go and support it natively.

The alternative approach is actually really simple. Because MSSQL already support SQL template strings (https://github.com/tediousjs/node-mssql/blob/5a4f77ac15ce66c89f6da168fddeeec3806b6360/lib/global-connection.js#L145-L146) you can actually just do `mssql.query(sql.strings, sql.values)`.

**Comment by blakeembrey** [comment]
This may be interesting for you too, since this is effectively the original proposal (they do it internally to support the template literal already): https://github.com/tediousjs/node-mssql/blob/72457687b3dd11d709ac5ff4ddced57154af2fc9/lib/base/request.js#L69-L95.

**Comment by blakeembrey** [comment]
That said, you are correct and this can’t be supported “magically” like the others. I’d be happy to put a recipe for this in the README though, since the second format is extremely simple and almost as easy as `query(sql)` from Postgres/MySQL. It’s definitely not obvious that it would work so easily without seeing how they implemented the template literals.

**Comment by madebysid** [comment]
@blakeembrey
> you can actually just do mssql.query(sql.strings, sql.values) which would be “faking” the template literal.

Ah interesting, I didn't look at `mssql.query`.

> This may be interesting for you too, since this is effectively the original proposal

Definitely is!

> this can’t be supported “magically” like the others.

Yep, I was hesitant to send a PR because of this (still am!) I also agree that your suggestion of adding a recipe for this in the README is probably the right way to go.

**Comment by blakeembrey** [comment]
Added a section in the README although it's probably incomplete: https://github.com/blakeembrey/sql-template-tag#recipes
