### ISSUE TITLE
`join` should ignore empty Sql

### ISSUE THREAD

**Issue by urugator** [blakeembrey/sql-template-tag#38]
Currently `join([empty(), empty(), empty()])` results in `,,`. I think it would make more sense and would be more useful if `join` would skip empty statements.

Eg:
```js
join([
  filterByFirstName ? sql`first_name LIKE ${firstName}` : empty(),
  filterByLastName ?  sql`last_name LIKE ${lastName}` : empty(),
  ],
  " AND "
);
```

**Comment by blakeembrey** [comment]
It's not a bad idea, but the performance implications for doing a filter every `join` instead of you just checking for it yourself doesn't seem worth it right now. For example, you can just do this:

```js
join([
  filterByFirstName ? sql`first_name LIKE ${firstName}` : null,
  filterByLastName ?  sql`last_name LIKE ${lastName}` : null,
  ].filter(Boolean),
  " AND "
);
```

If it's within the library I basically need to add that `.filter` to every `join` attempt because I use the array length to compute the number of commas to repeat.

**Comment by blakeembrey** [comment]
Another gotcha for adding this is that `join([])` throws an error today. What would `join([empty])` do? It seems odd and hard to debug that `[empty, empty]` would throw an error while the other 3 combinations would not.

**Comment by blakeembrey** [comment]
> isEmpty utility (strings.length === 1 && strings[0].length === 0) would be appreciated maybe.

Sure, I can accept a PR for this.

I still think clearly indicating an `undefined` or `null` value is going to make your life simpler in the long run, and it's easier for other engineers to understand the intent, but I think it's good to keep that outside the library.
