### ISSUE TITLE
Update the `About` section to include oracledb

### ISSUE THREAD

**Issue by sharadraju** [blakeembrey/sql-template-tag#47]
Since node-oracledb supports sql-template-tag, We request you to update the `About` section in the repo with oracledb as well

**Comment by blakeembrey** [comment]
Since [package.json](https://github.com/blakeembrey/sql-template-tag/blob/cccce03e19059f786aaedcebfba99186ab0ab082/package.json#L4) and README is already updated, I think it's just the GitHub description? Let me know if I missed anything or the tag could be a better one, here's the updated view:

![CleanShot 2024-12-13 at 11 14 07@2x](https://github.com/user-attachments/assets/50940f45-0642-4951-ade5-3e289ddd150f)
